image: python:3.6.0

pipelines:
  branches:
    master:
      - step:
          script:
            - echo "[pypi]" > ~/.pypirc
            - echo "username: $PYPI_USER" >> ./pypirc
            - echo "password: $PYPI_PASSWORD" >> ./pypirc
#            - cat ~/.pypirc
            # requires a new version in setup.py
            - python setup.py sdist bdist_wheel
            - twine upload dist/*
    develop:
      - step:
          script:
            - echo "[testpypi]" > ~/.pypirc
            - echo "username: $PYPI_TEST_USER" >> ./pypirc
            - echo "password: $PYPI_TEST_PASSWORD" >> ./pypirc
#            - cat ~/.pypirc
            # requires a new version in setup.py
            - python setup.py sdist bdist_wheel
            - twine upload --repository testpypi dist/*
