image: python:3.6.0

pipelines:
  branches:
    master:
      - step:
          script:
            - mv ./pypirc ~/.pypirc
            - echo "username = $ARTIFACTORY_USER" >> ~/.pypirc
            - echo "password=$ARTIFACTORY_PASSWORD" >> ~/.pypirc
            # requires a new version in setup.py
            - python setup.py sdist upload -r jfrog
