image: python:2.7.13

pipelines:
  branches:
    master:
      - step:
          script:
            - mv ./pypirc ~/.pypirc
            - echo 'username=$ARTIFACTORY_USER' >> ~/.pypirc
            - echo "password=$ARTIFACTORY_PASSWORD" >> ~/.pypirc
            # requires a new version in setup.py
            - python setup.py sdist upload -r jfrog
